version: '3.3'
services:
  postgres:
    restart: always
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
    - "5435:5432"
    hostname: postgres
  webserver:
    restart: always
    build:
      context: ./
    ports:
      - 8011:80
    volumes:
      - ./backend:/backend
      - ./backend/drinkif/static:/var/www/html
    environment:
      - environment=production
      - APP_NAME=drinkif
    depends_on:
      - postgres
