version: '3.3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
    - "5435:5432"
    hostname: postgres
    container_name: postgres
  webserver:
    restart: always
    build:
      context: ./
    ports:
      - 8111:8000
    volumes:
      - ./backend:/backend
    environment:
      - environment=production
      - APP_NAME=drinkif
    depends_on:
      - postgres