# Generated by Django 4.0.1 on 2022-01-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkif', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrases',
            old_name='phrase',
            new_name='creator',
        ),
    ]
