# Generated by Django 4.0.1 on 2022-01-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkif', '0003_friendship_fiendrequest_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='decscription',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
