# Generated by Django 4.0.1 on 2022-01-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkif', '0004_extendeduser_decscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='decscription',
            new_name='description',
        ),
    ]
