# Generated by Django 4.0.1 on 2022-01-11 21:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinkif', '0005_rename_decscription_extendeduser_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiendRequest',
            new_name='FriendshipRequest',
        ),
    ]
