# Generated by Django 4.0.1 on 2022-01-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkif', '0006_rename_fiendrequest_friendshiprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='friend',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='user',
            new_name='sender',
        ),
    ]
