# Generated by Django 3.2.6 on 2022-01-12 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinkif', '0007_rename_friend_friendshiprequest_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='accepted',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
