# Generated by Django 3.2.6 on 2022-01-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkif', '0009_extendeduser_is_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrases',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
